import { ArrowUpRight } from "lucide-react";
import Image from "next/image";
import type { FeaturesSectionProps, GallerySectionProps, HeroSectionProps, ImageSectionProps, LargeImageSectionProps, LinksSectionProps, MetricsSectionProps, StorySectionProps, TechStackSectionProps, TextImageSectionProps, TextSectionProps, VideoSectionProps } from "@/src/lib/project-schema";

type AssetResolver = (src: string) => string;
const ProjectImage = ({ src, alt, resolve }: { src: string; alt: string; resolve: AssetResolver }) => <div className="section-image-frame"><Image src={resolve(src)} alt={alt} fill sizes="(max-width: 768px) 100vw, 1200px" unoptimized /></div>;

export function ProjectHero({ props, resolve }: { props: HeroSectionProps; resolve: AssetResolver }) {
  return <section className="detail-section detail-hero"><div className="detail-copy"><span>{props.eyebrow}</span>{props.heading && <h2>{props.heading}</h2>}{props.body && <p>{props.body}</p>}</div>{props.image && <ProjectImage src={props.image} alt="" resolve={resolve} />}</section>;
}
export function TextSection({ props }: { props: TextSectionProps }) { return <section className="detail-section text-section"><h2>{props.heading}</h2><p>{props.body}</p></section>; }
export function ImageSection({ props, resolve }: { props: ImageSectionProps; resolve: AssetResolver }) { return <section className="detail-section image-section"><ProjectImage src={props.image} alt={props.alt} resolve={resolve} />{props.caption && <p className="section-caption">{props.caption}</p>}</section>; }
export function LargeImageSection({ props, resolve }: { props: LargeImageSectionProps; resolve: AssetResolver }) { return <section className="detail-section large-image-section"><ProjectImage src={props.image} alt={props.alt} resolve={resolve} />{props.caption && <p className="section-caption">{props.caption}</p>}</section>; }
export function TextImageSection({ props, resolve }: { props: TextImageSectionProps; resolve: AssetResolver }) { return <section className={`detail-section text-image-section image-${props.imagePosition}`}><div><h2>{props.heading}</h2><p>{props.body}</p></div><ProjectImage src={props.image} alt={props.alt} resolve={resolve} /></section>; }
export function GallerySection({ props, resolve }: { props: GallerySectionProps; resolve: AssetResolver }) { return <section className="detail-section gallery-section">{props.heading && <h2>{props.heading}</h2>}<div>{props.images.map((item, i) => <figure key={`${item.src}-${i}`}><ProjectImage src={item.src} alt={item.alt} resolve={resolve} />{item.caption && <figcaption>{item.caption}</figcaption>}</figure>)}</div></section>; }
export function VideoSection({ props, resolve }: { props: VideoSectionProps; resolve: AssetResolver }) { return <section className="detail-section video-section">{props.heading && <h2>{props.heading}</h2>}<video controls preload="metadata" poster={props.poster ? resolve(props.poster) : undefined}><source src={resolve(props.src)} /></video>{props.caption && <p className="section-caption">{props.caption}</p>}</section>; }
export function FeaturesSection({ props }: { props: FeaturesSectionProps }) { return <section className="detail-section list-section"><h2>{props.heading ?? "Features"}</h2><ol>{props.items.map((item, i) => <li key={item.title}><span>{String(i + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ol></section>; }
export function TechStackSection({ props }: { props: TechStackSectionProps }) { return <section className="detail-section list-section"><h2>{props.heading ?? "Technology"}</h2><ol>{props.items.map((item, i) => <li key={item.name}><span>{String(i + 1).padStart(2, "0")}</span><div><h3>{item.name}</h3><p>{item.purpose}</p></div></li>)}</ol></section>; }
export function LinksSection({ props }: { props: LinksSectionProps }) { const links = [...(props.website ? [{ label: "Website", url: props.website }] : []), ...(props.github ? [{ label: "GitHub", url: props.github }] : []), ...(props.links ?? [])]; return <section className="detail-section links-section"><h2>{props.heading ?? "Explore"}</h2><div>{links.map((link) => <a href={link.url} key={`${link.label}-${link.url}`}>{link.label}<ArrowUpRight aria-hidden="true" /></a>)}</div></section>; }
export function MetricsSection({ props }: { props: MetricsSectionProps }) { return <section className="detail-section metrics-section">{props.heading && <h2>{props.heading}</h2>}<dl>{props.items.map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></section>; }
export function StorySection({ props }: { props: StorySectionProps }) { const steps = [["Problem", props.problem], ["Idea", props.idea], ["Implementation", props.implementation], ...(props.result ? [["Result", props.result]] : [])]; return <section className="detail-section story-section"><header><span>From question to product</span><h2>{props.heading ?? "Why I built it"}</h2></header><ol>{steps.map(([label, text], index) => <li key={label}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{label}</h3><p>{text}</p></div></li>)}</ol></section>; }
